/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface StartupNode {
  'id' : string,
  'latitude' : number,
  'directive' : string,
  'ownerId' : Principal,
  'city' : string,
  'createdAt' : Time,
  'description' : string,
  'sector' : string,
  'longitude' : number,
  'companyName' : string,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'city' : string,
  'userId' : Principal,
  'name' : string,
  'sector' : string,
  'email' : string,
  'updatedAt' : Time,
  'startupName' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNode' : ActorMethod<
    [string, string, string, string, number, number, string],
    string
  >,
  'deleteNode' : ActorMethod<[string], string>,
  'getAllNodes' : ActorMethod<[], Array<StartupNode>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyNode' : ActorMethod<[], [] | [StartupNode]>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getProfileByUserId' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[], string>,
  'updateNode' : ActorMethod<
    [string, string, string, string, string, number, number, string],
    string
  >,
  'upsertProfile' : ActorMethod<
    [string, string, string, string, string, string, string],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];