/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const StartupNode = IDL.Record({
  'id' : IDL.Text,
  'latitude' : IDL.Float64,
  'directive' : IDL.Text,
  'ownerId' : IDL.Principal,
  'city' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'sector' : IDL.Text,
  'longitude' : IDL.Float64,
  'companyName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'city' : IDL.Text,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'sector' : IDL.Text,
  'email' : IDL.Text,
  'updatedAt' : Time,
  'startupName' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNode' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'deleteNode' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllNodes' : IDL.Func([], [IDL.Vec(StartupNode)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyNode' : IDL.Func([], [IDL.Opt(StartupNode)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getProfileByUserId' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedData' : IDL.Func([], [IDL.Text], []),
  'updateNode' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'upsertProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const StartupNode = IDL.Record({
    'id' : IDL.Text,
    'latitude' : IDL.Float64,
    'directive' : IDL.Text,
    'ownerId' : IDL.Principal,
    'city' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'sector' : IDL.Text,
    'longitude' : IDL.Float64,
    'companyName' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'city' : IDL.Text,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'sector' : IDL.Text,
    'email' : IDL.Text,
    'updatedAt' : Time,
    'startupName' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNode' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'deleteNode' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllNodes' : IDL.Func([], [IDL.Vec(StartupNode)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyNode' : IDL.Func([], [IDL.Opt(StartupNode)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getProfileByUserId' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedData' : IDL.Func([], [IDL.Text], []),
    'updateNode' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'upsertProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };